# Generated by Django 4.0.4 on 2022-06-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_burger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('drice', models.DecimalField(decimal_places=0, max_digits=4)),
                ('dImage', models.URLField()),
            ],
        ),
        
    ]
